# Generated by Django 5.2 on 2025-04-18 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_studied', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.CharField(max_length=100)),
                ('back', models.CharField(max_length=100)),
                ('last_review_date', models.DateTimeField()),
                ('next_review_date', models.DateTimeField()),
                ('deck_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.deck')),
            ],
        ),
    ]
