name: Pull Request Workflow

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: flashcards
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11.4
      uses: actions/setup-python@v4
      with:
        python-version: 3.11.4
    
    - name: Install dev dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    
    - name: Run migrations
      run: |
        python manage.py migrate
    
    - name: Run pylint
      run: |
        pylint --recursive=y .
    
    - name: Run tests
      run: |
        python manage.py test
